name: _linter
run-name: "linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reusable-linter:
    uses: ulfiac/commons/.github/workflows/reusable_linter.yaml@1ef698821e7809a85c4cdfecefa17a747164a251 # v1.0.47
