name: _linter
run-name: "linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reusable-linter:
    uses: ulfiac/commons/.github/workflows/reusable_linter.yaml@21601aa5ad70c1a590a49ca46769ee155f908456 # v1.0.48
