name: _purge_workflow_runs

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-workflow-runs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_runs.yaml@6080e6f56ab007982481e7f140254af58b002a97 # v1.0.58
