name: _purge_workflow_runs

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-workflow-runs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_runs.yaml@86f71e53e74747e558b50cb51c469bd371c045bf # v1.0.51
