name: _request_copilot_review
run-name: "_request_copilot_review: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: request-copilot-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  reusable-request-copilot-review:
    uses: ulfiac/commons/.github/workflows/reusable_request_copilot_review.yaml@c9a73fa7b2ca8c1117f4986e3a2fd12c92bc1aad # v1.0.46
    secrets:
      PAT_REQUEST_COPILOT_REVIEW: ${{ secrets.PAT_REQUEST_COPILOT_REVIEW }}
