name: _request_copilot_review
run-name: "_request_copilot_review: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: request-copilot-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  reusable-request-copilot-review:
    uses: ulfiac/commons/.github/workflows/reusable_request_copilot_review.yaml@28d0dd212f7ad742b74a9b42206351c9ce9aded5 # v1.0.42
    secrets:
      PAT_REQUEST_COPILOT_REVIEW: ${{ secrets.PAT_REQUEST_COPILOT_REVIEW }}
