name: _request_copilot_review
run-name: "_request_copilot_review: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: request-copilot-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  reusable-request-copilot-review:
    uses: ulfiac/commons/.github/workflows/reusable_request_copilot_review.yaml@9c2484fe0c766a56ff00e6f87830e638faaa7ce6 # v1.0.49
    secrets:
      PAT_REQUEST_COPILOT_REVIEW: ${{ secrets.PAT_REQUEST_COPILOT_REVIEW }}
