name: _terraform-docs
run-name: "terraform-docs: ${{ github.ref_name }}"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
      - '!terraform/modules/**/README.md'
  workflow_dispatch: {}

permissions: {}

jobs:
  terraform-docs:
    uses: ulfiac/commons/.github/workflows/reusable_terraform_docs.yaml@21601aa5ad70c1a590a49ca46769ee155f908456 # v1.0.48
    secrets:
      APP_CLIENT_ID: ${{ secrets.TERRAFORM_DOCS_BOT_APP_CLIENT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.TERRAFORM_DOCS_BOT_APP_PRIVATE_KEY }}
