name: _terraform-docs
run-name: "terraform-docs: ${{ github.ref_name }}"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
      - '!terraform/modules/**/README.md'
  workflow_dispatch: {}

permissions: {}

jobs:
  terraform-docs:
    uses: ulfiac/commons/.github/workflows/reusable_terraform_docs.yaml@c9a73fa7b2ca8c1117f4986e3a2fd12c92bc1aad # v1.0.46
    secrets:
      APP_CLIENT_ID: ${{ secrets.TERRAFORM_DOCS_BOT_APP_CLIENT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.TERRAFORM_DOCS_BOT_APP_PRIVATE_KEY }}
