name: deploy aws
run-name: "${{ inputs.terragrunt_action }}: aws, ${{ inputs.aws_account }}, ${{ inputs.aws_region }}, ${{ inputs.component }}"

on:
  workflow_dispatch:
    inputs:
      aws_account:
        default: all
        options:
          - all
          - mgmt
        required: true
        type: choice
      aws_region:
        default: all
        options:
          - all
          - _global
          - ca-central-1
          - us-east-1
          - us-east-2
        required: true
        type: choice
      component:
        default: all
        required: true
        type: string
      terragrunt_action:
        default: plan
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice
      dump_github_context:
        default: false
        required: false
        type: boolean
      skip_approval:
        default: false
        required: false
        type: boolean
      terragrunt_parallelism:
        default: true
        required: false
        type: boolean
      terragrunt_strict_mode:
        default: true
        required: false
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  set-plan-action:
    name: set plan action
    runs-on: ubuntu-24.04
    outputs:
      plan_action: ${{ steps.set-plan-action.outputs.plan_action }}
    steps:
      - name: set plan action
        id: set-plan-action
        run: |
          case "${{ inputs.terragrunt_action }}" in
            "plan"|"apply")
              echo "plan_action=plan" >> "$GITHUB_OUTPUT"
              ;;
            "plan destroy"|"destroy")
              echo "plan_action=plan destroy" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "Unexpected terragrunt_action: ${{ inputs.terragrunt_action }}"
              exit 1
              ;;
          esac

  plan:
    name: ${{ needs.set-plan-action.outputs.plan_action }}
    uses: ./.github/workflows/reusable_deploy_aws_accounts.yaml
    needs: set-plan-action
    with:
      aws_account: ${{ inputs.aws_account }}
      aws_region: ${{ inputs.aws_region }}
      component: ${{ inputs.component }}
      dump_github_context: ${{ inputs.dump_github_context }}
      terragrunt_action: ${{ needs.set-plan-action.outputs.plan_action }}
      terragrunt_parallelism: ${{ inputs.terragrunt_parallelism }}
      terragrunt_strict_mode: ${{ inputs.terragrunt_strict_mode }}
    secrets: inherit

  get-approval:
    name: get approval
    runs-on: ubuntu-24.04
    if: ${{ inputs.terragrunt_action == 'apply' || inputs.terragrunt_action == 'destroy' }}
    environment: ${{ inputs.skip_approval == true && 'approval_skipped' || 'approval_required' }}
    needs: plan
    steps:
      - name: approval requested
        run: echo 'Approval provided. Job will continue.'

  apply:
    name: ${{ inputs.terragrunt_action }}
    uses: ./.github/workflows/reusable_deploy_aws_accounts.yaml
    if: ${{ inputs.terragrunt_action == 'apply' || inputs.terragrunt_action == 'destroy' }}
    needs: get-approval
    with:
      aws_account: ${{ inputs.aws_account }}
      aws_region: ${{ inputs.aws_region }}
      component: ${{ inputs.component }}
      dump_github_context: ${{ inputs.dump_github_context }}
      terragrunt_action: ${{ inputs.terragrunt_action }}
      terragrunt_parallelism: ${{ inputs.terragrunt_parallelism }}
      terragrunt_strict_mode: ${{ inputs.terragrunt_strict_mode }}
    secrets: inherit
